# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tic_Tac_Toe.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
playflag=0
playerX=0
playerO=0



class Ui_Board(object):
    
    def resetcode(self):
        self.p1.setEnabled(True)
        self.p2.setEnabled(True)
        self.p3.setEnabled(True)
        self.p4.setEnabled(True)
        self.p5.setEnabled(True)
        self.p6.setEnabled(True)
        self.p7.setEnabled(True)
        self.p8.setEnabled(True)
        self.p9.setEnabled(True)
        self.p1.setText(' ')
        self.p2.setText(' ')
        self.p3.setText(' ')
        self.p4.setText(' ')
        self.p5.setText(' ')
        self.p6.setText(' ')
        self.p7.setText(' ')
        self.p8.setText(' ')
        self.p9.setText(' ')
    
    def btnclick(self,pos):
        global playflag
        mark=''
        if (playflag%2==0):
            mark='X'
        else:
            mark='O'
        if pos==1:
            self.p1.setText(mark)
            self.p1.setEnabled(False)
        if pos==2:
            self.p2.setText(mark)
            self.p2.setEnabled(False)
        if pos==3:
            self.p3.setText(mark)
            self.p3.setEnabled(False)
        if pos==4:
            self.p4.setText(mark)
            self.p4.setEnabled(False)
        if pos==5:
            self.p5.setText(mark)
            self.p5.setEnabled(False)
        if pos==6:
            self.p6.setText(mark)
            self.p6.setEnabled(False)
        if pos==7:
            self.p7.setText(mark)
            self.p7.setEnabled(False)
        if pos==8:
            self.p8.setText(mark)
            self.p8.setEnabled(False)
        if pos==9:
            self.p9.setText(mark)
            self.p9.setEnabled(False)
        playflag+=1
        self.checkin()
    def showdialog(self,msg):
        Dialog=QtWidgets.QMessageBox()
        Dialog.setText(msg)
        Dialog.setWindowTitle("Message")
        ret=Dialog.exec()

        
            
        
    def checkin(self):
        global playerX,playerO
        winner=' '
        if self.p1.text()==self.p2.text() and self.p2.text()==self.p3.text():
            winner=self.p1.text()
        elif self.p1.text()==self.p4.text() and self.p4.text()==self.p7.text():
            winner=self.p1.text()
        elif self.p2.text()==self.p5.text() and self.p5.text()==self.p8.text():
            winner=self.p2.text()
        elif self.p3.text()==self.p6.text() and self.p6.text()==self.p9.text():
            winner=self.p3.text()
        elif self.p4.text()==self.p5.text() and self.p5.text()==self.p6.text():
            winner=self.p4.text()
        elif self.p7.text()==self.p8.text() and self.p8.text()==self.p9.text():
            winner=self.p7.text()
        elif self.p1.text()==self.p5.text() and self.p5.text()==self.p9.text():
            winner=self.p1.text()
        elif self.p3.text()==self.p5.text() and self.p5.text()==self.p7.text():
            winner=self.p7.text()
        
        
        
        if winner=='X':
            playerX+=1
            self.playerx.setText("Player X:"+str(playerX))
            self.resetcode()
        if winner=='O':
            playerO+=1
            self.playero.setText("Player O: "+str(playerO))
            self.resetcode()
            
        
    def setupUi(self, Board):
        Board.setObjectName("Board")
        Board.resize(300, 400)
        self.centralwidget = QtWidgets.QWidget(Board)
        self.centralwidget.setObjectName("centralwidget")
        
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 301, 283))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        
        self.p4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p4.setMinimumSize(QtCore.QSize(93, 93))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.p4.setFont(font)
        self.p4.setText("")
        self.p4.setObjectName("p4")
        self.gridLayout.addWidget(self.p4, 0, 1, 1, 1)
        self.p4.clicked.connect(lambda:self.btnclick(4))
        
        self.p6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p6.setMinimumSize(QtCore.QSize(93, 93))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.p6.setFont(font)
        self.p6.setText("")
        self.p6.setObjectName("p6")
        self.gridLayout.addWidget(self.p6, 2, 1, 1, 1)
        self.p6.clicked.connect(lambda:self.btnclick(6))
        
        self.p3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p3.setMinimumSize(QtCore.QSize(93, 93))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.p3.setFont(font)
        self.p3.setText("")
        self.p3.setObjectName("p3")
        self.gridLayout.addWidget(self.p3, 2, 0, 1, 1)
        self.p3.clicked.connect(lambda:self.btnclick(3))
        
        self.p1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p1.setMinimumSize(QtCore.QSize(93, 93))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.p1.setFont(font)
        self.p1.setText("")
        self.p1.setObjectName("p1")
        self.gridLayout.addWidget(self.p1, 0, 0, 1, 1)
        self.p1.clicked.connect(lambda:self.btnclick(1))
        
        self.p2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p2.setMinimumSize(QtCore.QSize(93, 93))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.p2.setFont(font)
        self.p2.setText("")
        self.p2.setObjectName("p2")
        self.gridLayout.addWidget(self.p2, 1, 0, 1, 1)
        self.p2.clicked.connect(lambda:self.btnclick(2))
        
        self.p5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p5.setMinimumSize(QtCore.QSize(93, 93))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.p5.setFont(font)
        self.p5.setText("")
        self.p5.setObjectName("p5")
        self.gridLayout.addWidget(self.p5, 1, 1, 1, 1)
        self.p5.clicked.connect(lambda:self.btnclick(5))
        
        self.p7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p7.setMinimumSize(QtCore.QSize(93, 93))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.p7.setFont(font)
        self.p7.setText("")
        self.p7.setObjectName("p7")
        self.gridLayout.addWidget(self.p7, 0, 2, 1, 1)
        self.p7.clicked.connect(lambda:self.btnclick(7))
        
        self.p8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p8.setMinimumSize(QtCore.QSize(93, 93))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.p8.setFont(font)
        self.p8.setText("")
        self.p8.setObjectName("p8")
        self.gridLayout.addWidget(self.p8, 1, 2, 1, 1)
        self.p8.clicked.connect(lambda:self.btnclick(8))
        
        self.p9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p9.setMinimumSize(QtCore.QSize(93, 93))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.p9.setFont(font)
        self.p9.setText("")
        self.p9.setObjectName("p9")
        self.gridLayout.addWidget(self.p9, 2, 2, 1, 1)
        self.p9.clicked.connect(lambda:self.btnclick(9))
        
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(110, 310, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reset.setFont(font)
        self.reset.setObjectName("reset")
        self.reset.clicked.connect(self.resetcode)
        
        self.playerx = QtWidgets.QLabel(self.centralwidget)
        self.playerx.setGeometry(QtCore.QRect(20, 320, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.playerx.setFont(font)
        self.playerx.setObjectName("playerx")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 350, 81, 111))
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.playero = QtWidgets.QLabel(self.centralwidget)
        self.playero.setGeometry(QtCore.QRect(210, 320, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.playero.setFont(font)
        self.playero.setObjectName("playero")
        Board.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Board)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 20))
        self.menubar.setObjectName("menubar")
        Board.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Board)
        self.statusbar.setObjectName("statusbar")
        Board.setStatusBar(self.statusbar)

        self.retranslateUi(Board)
        QtCore.QMetaObject.connectSlotsByName(Board)

    def retranslateUi(self, Board):
        _translate = QtCore.QCoreApplication.translate
        Board.setWindowTitle(_translate("Board", "MainWindow"))
        self.reset.setText(_translate("Board", "RESET"))
        self.playerx.setText(_translate("Board", "Player X:0"))
        self.playero.setText(_translate("Board", "Player O:0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Board = QtWidgets.QMainWindow()
    ui = Ui_Board()
    ui.setupUi(Board)
    Board.show()
    sys.exit(app.exec_())
